import React from 'react';
import { Icon } from 'semantic-ui-react';

export const BRANDS = [
    { title: 'amazon', image: <Icon name="amazon" size="big" /> },
    { title: 'amazon pay', image: <Icon name="amazon pay" size="big" /> },
    { title: 'android', image: <Icon name="android" size="big" /> },
    { title: 'angellist', image: <Icon name="angellist" size="big" /> },
    { title: 'app store', image: <Icon name="app store" size="big" /> },
    {
        title: 'app store ios',
        image: <Icon name="app store ios" size="big" />,
    },
    { title: 'apple', image: <Icon name="apple" size="big" /> },
    { title: 'apple pay', image: <Icon name="apple pay" size="big" /> },
    { title: 'audible', image: <Icon name="audible" size="big" /> },
    { title: 'aws', image: <Icon name="aws" size="big" /> },
    { title: 'bandcamp', image: <Icon name="bandcamp" size="big" /> },
    { title: 'behance', image: <Icon name="behance" size="big" /> },
    {
        title: 'behance square',
        image: <Icon name="behance square" size="big" />,
    },
    { title: 'bimobject', image: <Icon name="bimobject" size="big" /> },
    { title: 'bitbucket', image: <Icon name="bitbucket" size="big" /> },
    { title: 'bitcoin', image: <Icon name="bitcoin" size="big" /> },
    { title: 'bity', image: <Icon name="bity" size="big" /> },
    { title: 'blackberry', image: <Icon name="blackberry" size="big" /> },
    { title: 'blogger', image: <Icon name="blogger" size="big" /> },
    { title: 'blogger b', image: <Icon name="blogger b" size="big" /> },
    { title: 'bluetooth', image: <Icon name="bluetooth" size="big" /> },
    { title: 'bluetooth b', image: <Icon name="bluetooth b" size="big" /> },
    { title: 'btc', image: <Icon name="btc" size="big" /> },
    {
        title: 'cc amazon pay',
        image: <Icon name="cc amazon pay" size="big" />,
    },
    { title: 'cc amex', image: <Icon name="cc amex" size="big" /> },
    { title: 'cc apple pay', image: <Icon name="cc apple pay" size="big" /> },
    {
        title: 'cc diners club',
        image: <Icon name="cc diners club" size="big" />,
    },
    { title: 'cc discover', image: <Icon name="cc discover" size="big" /> },
    { title: 'cc jcb', image: <Icon name="cc jcb" size="big" /> },
    {
        title: 'cc mastercard',
        image: <Icon name="cc mastercard" size="big" />,
    },
    { title: 'cc paypal', image: <Icon name="cc paypal" size="big" /> },
    { title: 'cc stripe', image: <Icon name="cc stripe" size="big" /> },
    { title: 'cc visa', image: <Icon name="cc visa" size="big" /> },
    { title: 'chrome', image: <Icon name="chrome" size="big" /> },
    { title: 'codepen', image: <Icon name="codepen" size="big" /> },
    {
        title: 'creative commons',
        image: <Icon name="creative commons" size="big" />,
    },
    { title: 'deviantart', image: <Icon name="deviantart" size="big" /> },
    { title: 'digg', image: <Icon name="digg" size="big" /> },
    {
        title: 'digital ocean',
        image: <Icon name="digital ocean" size="big" />,
    },
    { title: 'discord', image: <Icon name="discord" size="big" /> },
    { title: 'docker', image: <Icon name="docker" size="big" /> },
    { title: 'dribbble', image: <Icon name="dribbble" size="big" /> },
    {
        title: 'dribbble square',
        image: <Icon name="dribbble square" size="big" />,
    },
    { title: 'dropbox', image: <Icon name="dropbox" size="big" /> },
    { title: 'drupal', image: <Icon name="drupal" size="big" /> },
    { title: 'ember', image: <Icon name="ember" size="big" /> },
    { title: 'empire', image: <Icon name="empire" size="big" /> },
    { title: 'ethereum', image: <Icon name="ethereum" size="big" /> },
    { title: 'etsy', image: <Icon name="etsy" size="big" /> },
    { title: 'facebook', image: <Icon name="facebook" size="big" /> },
    { title: 'facebook f', image: <Icon name="facebook f" size="big" /> },
    {
        title: 'facebook messenger',
        image: <Icon name="facebook messenger" size="big" />,
    },
    {
        title: 'facebook square',
        image: <Icon name="facebook square" size="big" />,
    },
    { title: 'firefox', image: <Icon name="firefox" size="big" /> },
    { title: 'flickr', image: <Icon name="flickr" size="big" /> },
    { title: 'flipboard', image: <Icon name="flipboard" size="big" /> },
    { title: 'foursquare', image: <Icon name="foursquare" size="big" /> },
    {
        title: 'free code camp',
        image: <Icon name="free code camp" size="big" />,
    },
    { title: 'git', image: <Icon name="git" size="big" /> },
    { title: 'git square', image: <Icon name="git square" size="big" /> },
    { title: 'github', image: <Icon name="github" size="big" /> },
    {
        title: 'github alternate',
        image: <Icon name="github alternate" size="big" />,
    },
    {
        title: 'github square',
        image: <Icon name="github square" size="big" />,
    },
    { title: 'gitkraken', image: <Icon name="gitkraken" size="big" /> },
    { title: 'gitlab', image: <Icon name="gitlab" size="big" /> },
    { title: 'goodreads', image: <Icon name="goodreads" size="big" /> },
    { title: 'goodreads g', image: <Icon name="goodreads g" size="big" /> },
    { title: 'google', image: <Icon name="google" size="big" /> },
    { title: 'google drive', image: <Icon name="google drive" size="big" /> },
    { title: 'google play', image: <Icon name="google play" size="big" /> },
    { title: 'google plus', image: <Icon name="google plus" size="big" /> },
    {
        title: 'google plus g',
        image: <Icon name="google plus g" size="big" />,
    },
    {
        title: 'google plus square',
        image: <Icon name="google plus square" size="big" />,
    },
    {
        title: 'google wallet',
        image: <Icon name="google wallet" size="big" />,
    },
    { title: 'hooli', image: <Icon name="hooli" size="big" /> },
    { title: 'instagram', image: <Icon name="instagram" size="big" /> },
    { title: 'itunes', image: <Icon name="itunes" size="big" /> },
    { title: 'itunes note', image: <Icon name="itunes note" size="big" /> },
    { title: 'jenkins', image: <Icon name="jenkins" size="big" /> },
    { title: 'joomla', image: <Icon name="joomla" size="big" /> },
    { title: 'jsfiddle', image: <Icon name="jsfiddle" size="big" /> },
    { title: 'keycdn', image: <Icon name="keycdn" size="big" /> },
    { title: 'kickstarter', image: <Icon name="kickstarter" size="big" /> },
    {
        title: 'kickstarter k',
        image: <Icon name="kickstarter k" size="big" />,
    },
    { title: 'laravel', image: <Icon name="laravel" size="big" /> },
    { title: 'linkedin', image: <Icon name="linkedin" size="big" /> },
    { title: 'lyft', image: <Icon name="lyft" size="big" /> },
    { title: 'magento', image: <Icon name="magento" size="big" /> },
    { title: 'medium', image: <Icon name="medium" size="big" /> },
    { title: 'medium m', image: <Icon name="medium m" size="big" /> },
    { title: 'meetup', image: <Icon name="meetup" size="big" /> },
    { title: 'microsoft', image: <Icon name="microsoft" size="big" /> },
    { title: 'mix', image: <Icon name="mix" size="big" /> },
    { title: 'mixcloud', image: <Icon name="mixcloud" size="big" /> },
    { title: 'napster', image: <Icon name="napster" size="big" /> },
    {
        title: 'nintendo switch',
        image: <Icon name="nintendo switch" size="big" />,
    },
    { title: 'npm', image: <Icon name="npm" size="big" /> },
    { title: 'nutritionix', image: <Icon name="nutritionix" size="big" /> },
    { title: 'patreon', image: <Icon name="patreon" size="big" /> },
    { title: 'paypal', image: <Icon name="paypal" size="big" /> },
    { title: 'periscope', image: <Icon name="periscope" size="big" /> },
    { title: 'php', image: <Icon name="php" size="big" /> },
    { title: 'pied piper', image: <Icon name="pied piper" size="big" /> },
    {
        title: 'pied piper alternate',
        image: <Icon name="pied piper alternate" size="big" />,
    },
    {
        title: 'pied piper pp',
        image: <Icon name="pied piper pp" size="big" />,
    },
    { title: 'pinterest', image: <Icon name="pinterest" size="big" /> },
    { title: 'pinterest p', image: <Icon name="pinterest p" size="big" /> },
    {
        title: 'pinterest square',
        image: <Icon name="pinterest square" size="big" />,
    },
    { title: 'playstation', image: <Icon name="playstation" size="big" /> },
    { title: 'quora', image: <Icon name="quora" size="big" /> },
    { title: 'reddit', image: <Icon name="reddit" size="big" /> },
    { title: 'reddit alien', image: <Icon name="reddit alien" size="big" /> },
    {
        title: 'reddit square',
        image: <Icon name="reddit square" size="big" />,
    },
    { title: 'replyd', image: <Icon name="replyd" size="big" /> },
    { title: 'rocketchat', image: <Icon name="rocketchat" size="big" /> },
    { title: 'skype', image: <Icon name="skype" size="big" /> },
    { title: 'slack', image: <Icon name="slack" size="big" /> },
    { title: 'slack hash', image: <Icon name="slack hash" size="big" /> },
    { title: 'slideshare', image: <Icon name="slideshare" size="big" /> },
    { title: 'snapchat', image: <Icon name="snapchat" size="big" /> },
    {
        title: 'snapchat ghost',
        image: <Icon name="snapchat ghost" size="big" />,
    },
    {
        title: 'snapchat square',
        image: <Icon name="snapchat square" size="big" />,
    },
    { title: 'soundcloud', image: <Icon name="soundcloud" size="big" /> },
    { title: 'spotify', image: <Icon name="spotify" size="big" /> },
    {
        title: 'stack exchange',
        image: <Icon name="stack exchange" size="big" />,
    },
    {
        title: 'stack overflow',
        image: <Icon name="stack overflow" size="big" />,
    },
    { title: 'staylinked', image: <Icon name="staylinked" size="big" /> },
    { title: 'steam', image: <Icon name="steam" size="big" /> },
    { title: 'steam square', image: <Icon name="steam square" size="big" /> },
    { title: 'steam symbol', image: <Icon name="steam symbol" size="big" /> },
    { title: 'stripe', image: <Icon name="stripe" size="big" /> },
    { title: 'stripe s', image: <Icon name="stripe s" size="big" /> },
    { title: 'stumbleupon', image: <Icon name="stumbleupon" size="big" /> },
    {
        title: 'stumbleupon circle',
        image: <Icon name="stumbleupon circle" size="big" />,
    },
    { title: 'telegram', image: <Icon name="telegram" size="big" /> },
    {
        title: 'telegram plane',
        image: <Icon name="telegram plane" size="big" />,
    },
    { title: 'trello', image: <Icon name="trello" size="big" /> },
    { title: 'tripadvisor', image: <Icon name="tripadvisor" size="big" /> },
    { title: 'tumblr', image: <Icon name="tumblr" size="big" /> },
    {
        title: 'tumblr square',
        image: <Icon name="tumblr square" size="big" />,
    },
    { title: 'twitch', image: <Icon name="twitch" size="big" /> },
    { title: 'twitter', image: <Icon name="twitter" size="big" /> },
    {
        title: 'twitter square',
        image: <Icon name="twitter square" size="big" />,
    },
    { title: 'uber', image: <Icon name="uber" size="big" /> },
    { title: 'vimeo', image: <Icon name="vimeo" size="big" /> },
    { title: 'vimeo square', image: <Icon name="vimeo square" size="big" /> },
    { title: 'vimeo v', image: <Icon name="vimeo v" size="big" /> },
    { title: 'vine', image: <Icon name="vine" size="big" /> },
    { title: 'vk', image: <Icon name="vk" size="big" /> },
    { title: 'wechat', image: <Icon name="wechat" size="big" /> },
    { title: 'weibo', image: <Icon name="weibo" size="big" /> },
    { title: 'whatsapp', image: <Icon name="whatsapp" size="big" /> },
    {
        title: 'whatsapp square',
        image: <Icon name="whatsapp square" size="big" />,
    },
    { title: 'wikipedia w', image: <Icon name="wikipedia w" size="big" /> },
    { title: 'xbox', image: <Icon name="xbox" size="big" /> },
    { title: 'y combinator', image: <Icon name="y combinator" size="big" /> },
    { title: 'yahoo', image: <Icon name="yahoo" size="big" /> },
    { title: 'yelp', image: <Icon name="yelp" size="big" /> },
    { title: 'youtube', image: <Icon name="youtube" size="big" /> },
    {
        title: 'youtube square',
        image: <Icon name="youtube square" size="big" />,
    },
];

export const ICONS = [...BRANDS];
